fix: commiting

diff --git a/tm/raw_qcow2/snap_delete b/tm/raw_qcow2/snap_delete
--- a/tm/raw_qcow2/snap_delete
+++ b/tm/raw_qcow2/snap_delete
@@ -101,6 +101,11 @@ NEW_SNAP_LIST=( "${SNAP_LIST[@]/$SNAP_ID}" )
 FS_SNAP_LIST=( $(find $SNAP_DIR -mindepth 1 -maxdepth 1 -name '[0-9]*' -printf '%f\n' ))
 ACTIVE_SNAP_ID="$(basename $(readlink -f $DISK_PATH))"
 
+if [ ! -f "${DISK_PATH}" ]; then
+    log "Error deleting snapshot: Active snapshot is not exist!"
+    exit 3
+fi
+
 for ID in ${FS_SNAP_LIST[@]}; do
     eval SNAP${ID}_PATH="${SNAP_DIR}/${ID}"
     eval SNAP${ID}_PATH_SHORT="${SNAP_DIR_SHORT}/${ID}"
@@ -111,14 +116,10 @@ for ID in ${FS_SNAP_LIST[@]}; do
          exit 1
     fi
 
-    # TODO: Fix it
-    eval SNAP${ID}_PARENT_PATH_SHORT='$(echo ${SNAP'${ID}'_PARENT_PATH_SHORT} | awk -F '\'${SYSTEM_DS_DISK_PATH_SHORT}\'' '\''{print "'${SYSTEM_DS_DISK_PATH_SHORT}'" $NF}'\'')'
+    eval SNAP${ID}_PARENT_PATH_SHORT='$(echo ${SNAP'${ID}'_PARENT_PATH} | awk -F "'${SYSTEM_DS_DISK_PATH_SHORT}'" '\''{print "'${SYSTEM_DS_DISK_PATH_SHORT}'" $NF}'\'')'
 
-    eval echo ++++ SNAP${ID}_PARENT_PATH=\${SNAP${ID}_PARENT_PATH} >> /tmp/123
-    eval echo ++++ SNAP${ID}_PARENT_PATH_SHORT=\${SNAP${ID}_PARENT_PATH_SHORT} >> /tmp/123
-    
     # Get snapshot parent from image file
-    eval SNAP${ID}_PARENT='${SNAP'${ID}'_PARENT:-$(basename $SNAP'${ID}'_PARENT_PATH)}'
+    eval SNAP${ID}_PARENT='$(basename $SNAP'${ID}'_PARENT_PATH)'
 
     # Get snapshot childrens from image file
     eval PARENT="\${SNAP${ID}_PARENT}"
@@ -235,6 +236,12 @@ for ID in ${FS_SNAP_LIST[@]}; do
 
 done
 
+# Sort lists from end to beginning
+SNAP_COMMIT_LIST=($(echo ${SNAP_COMMIT_LIST[@]} | tr " " "\n" | sort -ur ))
+SNAP_DELETE_LIST=($(echo ${SNAP_DELETE_LIST[@]} | tr " " "\n" | sort -ur ))
+
+echo  >> /tmp/123
+echo "ACTIVE_SNAP_ID=${ACTIVE_SNAP_ID}" >> /tmp/123
 echo "SNAP_LIST=${SNAP_LIST[@]}" >> /tmp/123
 echo "NEW_SNAP_LIST=${NEW_SNAP_LIST[@]}" >> /tmp/123
 echo "FS_SNAP_LIST=${FS_SNAP_LIST[@]}" >> /tmp/123
@@ -248,7 +255,9 @@ echo "SNAP_DELETE_LIST=${SNAP_DELETE_LIST[@]}" >> /tmp/123
 ONLINE_COMMIT_CMD+='set -ex -o pipefail; '
 
 for ID in ${SNAP_COMMIT_LIST[@]}; do
+eval SNAP_PATH="\$SNAP${ID}_PATH"
 eval SNAP_PATH_SHORT="\$SNAP${ID}_PATH_SHORT"
+eval SNAP_PARENT_PATH="\$SNAP${ID}_PARENT_PATH"
 eval SNAP_PARENT_PATH_SHORT="\$SNAP${ID}_PARENT_PATH_SHORT"
 eval echo ++++ SNAP_PARENT_PATH_SHORT="\$SNAP${ID}_PARENT_PATH_SHORT" >> /tmp/123
 
@@ -257,14 +266,14 @@ ONLINE_COMMIT_CMD+=$(cat <<EOT
     # Correct SNAP_PATH
     SNAP_PATH=\$(virsh dumpxml $DOMAIN | xmlstarlet sel -t -v "//*/source/@file" | grep "$SNAP_PATH_SHORT\$")
     DISK_PATH=\$(virsh dumpxml $DOMAIN | xmlstarlet sel -t -v "/domain/devices/disk[.//@file='\${SNAP_PATH}']/source/@file")
-    SNAP_PARENT_PATH=\$(virsh dumpxml $DOMAIN | xmlstarlet sel -t -v "//*/source/@file" | grep "$SNAP_PARENT_PATH_SHORT\$")
+    SNAP_PARENT_PATH="$SNAP_PARENT_PATH"
     
     if [ "\$SNAP_PATH" == "\$DISK_PATH" ]; then
         virsh blockcommit $DOMAIN --path "\${DISK_PATH}" --top "\${SNAP_PATH}" --base "\${SNAP_PARENT_PATH}" --active --wait --pivot &&
-        rm -f \${SNAP_PATH}
+        rm -f \${SNAP_PATH} || exit 2
     else
         virsh blockcommit $DOMAIN --path "\${DISK_PATH}" --top "\${SNAP_PATH}" --base "\${SNAP_PARENT_PATH}" --wait &&
-        rm -f \${SNAP_PATH}
+        rm -f \${SNAP_PATH} || exit 2
     fi
     
 EOT
@@ -275,8 +284,7 @@ if [ ! -z "$NEW_ACTIVE_SNAP_PATH_SHORT" ]; then
     ONLINE_COMMIT_CMD+="ln -sf ${NEW_ACTIVE_SNAP_PATH_SHORT} ${SYSTEM_DS_DISK_PATH}; "
 fi
 
-    echo "NEW_ACTIVE_SNAP_PATH_SHORT=$NEW_ACTIVE_SNAP_PATH_SHORT
-          {#NEW_SNAP_LIST[@]}=${#NEW_SNAP_LIST[@]}" > /tmp/1234
+    echo "$ONLINE_COMMIT_CMD" > /tmp/1234
     
 
 #-------------------------------------------------------------------------------
