fix: run script fully in host

diff --git a/tm/raw_qcow2/snap_delete b/tm/raw_qcow2/snap_delete
--- a/tm/raw_qcow2/snap_delete
+++ b/tm/raw_qcow2/snap_delete
@@ -102,7 +102,7 @@ NEW_SNAP_LIST=( "${SNAP_LIST[@]/$SNAP_ID}" )
 COMMON_COMMIT_CMD=$(cat <<EOT
 set -ex -o pipefail
 
-FS_SNAP_LIST=( \$(find $SNAP_DIR -mindepth 1 -maxdepth 1 -name '[0-9]*' -printf '%f\n' ))
+FS_SNAP_LIST=( \$(find $SNAP_DIR -mindepth 1 -maxdepth 1 -name '[0-9]*' -printf '%f\\n' ))
 ACTIVE_SNAP_ID="\$(basename \$(readlink -f $DISK_PATH))"
 
 if [ ! -f "${DISK_PATH}" ]; then
@@ -113,27 +113,24 @@ fi
 for ID in \${FS_SNAP_LIST[@]}; do
     eval SNAP\${ID}_PATH="${SNAP_DIR}/\${ID}"
     eval SNAP\${ID}_PATH_SHORT="${SNAP_DIR_SHORT}/\${ID}"
-    eval SNAP\${ID}_INFO_JSON='\$(qemu-img info --output=json \${SNAP'\${ID}'_PATH})'
+    eval IFS='' SNAP\${ID}_INFO_JSON="\\\$(qemu-img info --output=json \\\${SNAP\${ID}_PATH})"
     if [ -z "\$(eval echo \\\$SNAP\${ID}_INFO_JSON)" ]; then
-         eval log '"Error deleting snapshot: Command execution failed: \\\"qemu-img info --output=json \${SNAP'\${ID}'_PATH}\\\""'
+         eval log '"Error deleting snapshot: Command execution failed: \\"qemu-img info --output=json \${SNAP'\${ID}'_PATH}\\""'
          exit 1
     fi
 
-    eval SNAP\${ID}_PARENT_PATH='\$(echo "\$SNAP'\${ID}'_INFO_JSON" | python -c "import sys, json; print(json.load(sys.stdin)['\\\''full-backing-filename'\\\''])")'
+    eval SNAP\${ID}_PARENT_PATH="\\\$(echo "\\\$SNAP\${ID}_INFO_JSON" | awk -F'[, \\t=:\"]*' '\\\$2 == \"full-backing-filename\" {print \\\$3}')"
     if [[ -z "\$(eval echo \\\$SNAP\${ID}_PARENT_PATH)" ]]; then
-        eval SNAP\${ID}_PARENT_PATH='\$(echo "\$SNAP'\${ID}'_INFO_JSON" | python -c "import sys, json; print(json.load(sys.stdin)['\\\''backing-filename'\\\''])")'
+        eval SNAP\${ID}_PARENT_PATH="\\\$(echo "\\\$SNAP\${ID}_INFO_JSON" | awk -F'[, \\t=:\"]*' '\\\$2 == \"backing-filename\" {print \\\$3}')"
     fi
 
-    eval echo SNAP\${ID}_PARENT_PATH=\\\$SNAP\${ID}_PARENT_PATH >> /tmp/123
+    if [[ ! -z "\$(eval echo \\\$SNAP\${ID}_PARENT_PATH)" ]]; then
+        eval SNAP\${ID}_PARENT_PATH_SHORT='\$(echo \${SNAP'\${ID}'_PARENT_PATH} | awk -F "'\${SYSTEM_DS_DISK_PATH_SHORT}'" '\\''{print "'\${SYSTEM_DS_DISK_PATH_SHORT}'" \$NF}'\\'')'
+        eval SNAP\${ID}_PARENT="\\\$(basename \\\$SNAP\${ID}_PARENT_PATH)"
+        eval PARENT="\\\${SNAP\${ID}_PARENT}"
+        eval SNAP\${PARENT}_CHILDREN+=\' \${ID}\'
+    fi
 
-    eval SNAP\${ID}_PARENT_PATH_SHORT='\$(echo \${SNAP'\${ID}'_PARENT_PATH} | awk -F "'\${SYSTEM_DS_DISK_PATH_SHORT}'" '\\\''{print "'\${SYSTEM_DS_DISK_PATH_SHORT}'" \$NF}'\\\'')'
-
-    # Get snapshot parent from image file
-    eval SNAP\${ID}_PARENT='\$(basename \$SNAP'\${ID}'_PARENT_PATH)'
-
-    # Get snapshot childrens from image file
-    eval PARENT="\\\${SNAP\${ID}_PARENT}"
-    eval SNAP\${PARENT}_CHILDREN+=\\\" \${ID}\\\"
 done
 
 if [[ -z "${NEW_SNAP_LIST[@]}" ]]; then
@@ -259,21 +256,21 @@ for ID in \${SNAP_COMMIT_LIST[@]}; do
     eval SNAP_PARENT_PATH_SHORT="\\\$SNAP\${ID}_PARENT_PATH_SHORT"
 
     # Correct SNAP_PATH
-    SNAP_PATH=\$(virsh dumpxml $DOMAIN | xmlstarlet sel -t -v "//*/source/@file" | grep "$SNAP_PATH_SHORT\$")
+    SNAP_PATH=\$(virsh dumpxml $DOMAIN | xmlstarlet sel -t -v "//*/source/@file" | grep -m1 "\$SNAP_PATH_SHORT\\$")
     DISK_PATH=\$(virsh dumpxml $DOMAIN | xmlstarlet sel -t -v "/domain/devices/disk[.//@file='\${SNAP_PATH}']/source/@file")
-    SNAP_PARENT_PATH=\$(virsh dumpxml $DOMAIN | xmlstarlet sel -t -v "//*/source/@file" | grep "$SNAP_PARENT_PATH_SHORT\$")
+    SNAP_PARENT_PATH=\$(virsh dumpxml $DOMAIN | xmlstarlet sel -t -v "//*/source/@file" | grep -m1 "\$SNAP_PARENT_PATH_SHORT\\$")
     
     if [ "\$SNAP_PATH" == "\$DISK_PATH" ]; then
         virsh blockcommit $DOMAIN --path "\${DISK_PATH}" --top "\${SNAP_PATH}" --base "\${SNAP_PARENT_PATH}" --active --wait --pivot &&
-        rm -f \${SNAP_PATH} || exit 2
+        rm -f \${SNAP_PATH} || exit 4
     else
         virsh blockcommit $DOMAIN --path "\${DISK_PATH}" --top "\${SNAP_PATH}" --base "\${SNAP_PARENT_PATH}" --wait &&
-        rm -f \${SNAP_PATH} || exit 2
+        rm -f \${SNAP_PATH} || exit 4
     fi
     
 done
 
-ln -sf '\${NEW_ACTIVE_SNAP_PATH_SHORT}' '\${SYSTEM_DS_DISK_PATH}';
+ln -sf '\${NEW_ACTIVE_SNAP_PATH_SHORT}' '${SYSTEM_DS_DISK_PATH}'
 
 EOT
 )
@@ -308,7 +305,7 @@ for ID in \${SNAP_COMMIT_LIST[@]}; do
     
 done
 
-ln -sf '\${NEW_ACTIVE_SNAP_PATH_SHORT}' '\${SYSTEM_DS_DISK_PATH}';
+ln -sf '\${NEW_ACTIVE_SNAP_PATH_SHORT}' '${SYSTEM_DS_DISK_PATH}'
 
 EOT
 )
